zendesk/active_record_host_pool

- Rakefile
- gemfiles/ar_32.gemfile.lock
- gemfiles/ar_40.gemfile.lock
- gemfiles/ar_41.gemfile.lock
- gemfiles/ar_42.gemfile.lock
- lib/active_record_host_pool/pool_proxy.rb
- test/test_arhp.rb
- test/test_arhp_wrong_db.rb
This fixes rake db:create failing to create a database because the original connection references a database that doesn't exist. Upon
establishing a new connection to `:database => nil`, the original connection is re-used and throws the same error: "Unknown database".
~~An alternate fix would be modify the `_pool_key` to include `@config[:database]`, but that may diminish the value of this proxy.~~ :smile: 
References:
* https://github.com/rails/rails/blob/v3.2.21/activerecord/lib/active_record/railties/databases.rake#L120
/cc @osheroff @grosser @kencheeto
> Ensures invalid connections are not re-used.

- gemfiles/ar_32.gemfile.lock
- gemfiles/ar_40.gemfile.lock
- gemfiles/ar_41.gemfile.lock
- gemfiles/ar_42.gemfile.lock
- lib/active_record_host_pool/pool_proxy.rb
- test/database.yml
- test/test_arhp_wrong_db.rb
Turns out my test didn't completely exercise the code the same way `rake
db:reset` exercises the code. Here's why the test was inadequate:
1. It runs `TestNotThere.establish_connection` followed by
`TestNotThere.connection`, which properly removes the invalid connection
to `arhp_test_no_create` from the connection pool.
2. Then it runs `Test1.establish_connection(:test_host_1_db_1)`
(database: `arhp_test_1`).
3. This invokes
https://github.com/rails/rails/blob/v3.2.21/activerecord/lib/active_record/connection_adapters/abstract/connection_specification.rb#L136
4. Which invokes
https://github.com/rails/rails/blob/v3.2.21/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L429
5. Which invokes `self.__getobj__` …
> Redux: Ensures invalid connections are not re-used

- lib/active_record_host_pool/pool_proxy.rb
When accessing a `HashWithIndifferentAccess` with a symbol key, a string is created by calling `to_s` on the symbol. If you call `#[:database]` 700 times in a row (yes, this happens), 700 separate instances of the string `"database"` will need garbage collection later on…
I looked at `ActiveRecord::ConnectionAdapters::ConnectionPool` source all the way from v2.2.0 up to the current master, and everywhere, the connection configuration is accessed using a symbol and not a string. So I don't see the need for calling `with_indifferent_access` on the configuration hash.
cc @osheroff @grosser
> Don't call #with_indifferent_access on the config

- lib/active_record_host_pool/pool_proxy.rb
- test/database.yml
- test/helper.rb
- test/test_arhp.rb
Currently when integrating with https://github.com/zendesk/active_record_shards if you don't specify different `:host` values in database.yml for the masters vs the slaves (because you're relying on flex master's `:hosts` entry to auto-detect the master), any `on_slave` calls will always return the existing connection pool for the master instead. This change introduces a conceptual coupling to ARS/FM, but does not impact anyone not using our garden of database gems, and is more simple than implementing a generic interface for this scenario. I stumbled on this when testing code in staging, but it could easily cause a major production issue if someone wasn't aware of the behavior.
/cc @steved @osheroff @bquorning @grosser
> Reliable active_record_shards / flexmaster slave selection

- Gemfile
- lib/active_record_host_pool/connection_adapter_mixin.rb
patch @config[:database] sooner in the stack
I can't seem to get a test working that proves this, but later versions of the mysql2 adapter use `config[:database]` to generate SQL queries for stuff like `.primary_key`; so as soon as we access the connection at all we should slam the database into the configuration var.
@bquorning
> primary key issues

- .rubocop.yml
- .travis.yml
- active_record_host_pool.gemspec
- gemfiles/rails3.2.gemfile
- gemfiles/rails4.2.gemfile
- gemfiles/rails5.0.gemfile
- gemfiles/rails5.2.gemfile
- gemfiles/rails5.2.gemfile.lock
- test/helper.rb
- test/test_arhp.rb
- test/test_arhp_wrong_db.rb
/cc @zendesk/zendesk-rails-upgraders
> Compatibility with Rails 5.2

- active_record_host_pool.gemspec
- gemfiles/rails3.2.gemfile.lock
- gemfiles/rails4.2.gemfile.lock
- gemfiles/rails5.0.gemfile.lock
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- lib/active_record_host_pool/connection_adapter_mixin.rb
- lib/active_record_host_pool/pool_proxy.rb
Last release of mysql gem was 5 years ago, and MysqlAdapter was removed in Rails 5.0. I doubt anyone uses active_record_host_pool together with the mysql gem.
> Just support mysql2, not mysql gem

- .github/CODEOWNERS
- active_record_host_pool.gemspec
Adds current maintainers to gemspec, but keep names of previous contributors.
> Add information on current gem maintainers

- .circleci/config.yml
We don’t save a whole lot of CI seconds, but it seems like good practice.
> Use ram mysql when testing

- active_record_host_pool.gemspec
Versions < 0.62 are not compatible with Ruby 2.6: https://circleci.com/gh/zendesk/active_record_host_pool/287
> Upgrade RuboCop

- .circleci/config.yml
Our builds started failing for no obvious reason, turns out a new Debian image was released in July this year https://en.wikipedia.org/wiki/Debian_version_history#Debian_10_(Buster)
This patch locks down the Debian image to `stretch`, which is what we were using before. You can find the list of supported images for Circle CI here:
https://circleci.com/docs/2.0/circleci-images/#ruby
We can move when ready and not run into seemingly random failures next time an update gets rolled out. (Although it could be a couple of years 😅)
> Lock down OS images in tests to fix build

- .circleci/config.yml
This package is outdated and no longer exists in newer Debian images, it'll be a blocker for us when we eventually move to Debian (buster)
https://packages.debian.org/stretch/mysql-client
> This is a transitional MySQL database that depends on default MySQL client metapackage. It can be safely removed.
https://packages.debian.org/stretch/default-mysql-client
> MySQL is a fast, stable and true multi-user, multi-threaded SQL database server. SQL (Structured Query Language) is the most popular database query language in the world. The main goals of MySQL are speed, robustness and ease of use.
> [CI] Update "mysql-client" to "default-mysql-client"

- gemfiles/rails4.2.gemfile.lock
- gemfiles/rails5.0.gemfile.lock
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- lib/active_record_host_pool/version.rb
I'm looking at making some changes to this gem to support Rails 5.2.3 and in doing so noticed that there are a few changes on master that haven't been released yet.
Releasing the diff between master and 0.11.0 in isolation.
Diff https://github.com/zendesk/active_record_host_pool/compare/v0.11.0...d75c570
> Bump active_record_host_pool to 0.12.0

- Readme.md
- lib/active_record_host_pool/pool_proxy.rb
- test/test_arhp.rb
Upon upgrading to Rails 5.2.3 and using v0.11.0 of this gem I received exceptions when a forked process attempted to communicate to the database. 
I could reproduce the behaviour with `config.cache_classes = config.eager_load = true`  set in my `config/environment/development.rb` and executing  `rails runner "Process.fork { ActiveRecord::Base.connected? }"`
Rails has modified the way it handles database connections in
* rails/rails#31173 
* rails/rails#28057 
* rails/rails#31221
This patch adds supports to this gem for Rails 5.2.3 with the following 
* Don't auto-create connection if nil on methods 5916c96
* Clear entry from PoolProxy when Rails discards a ConnectionPool 460b4d1
> Add support for Rails 5.2.3

- .circleci/config.yml
- Changelog.md
- active_record_host_pool.gemspec
- gemfiles/rails5.0.gemfile.lock
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- gemfiles/rails6.0.gemfile
- gemfiles/rails6.0.gemfile.lock
- lib/active_record_host_pool/connection_adapter_mixin.rb
It looks like Rails 6 works with the same `#establish_connection` implementation as for Rails 5.2.
> Rails 6 compatibility

- Changelog.md
- lib/active_record_host_pool/version.rb
No drastic changes, just a bump to v1.0.0 to signal that this project has a stable API.
From here on, we keep a changelog and adhere to semantic versioning.
Fixes #51
> Release v1.0.0

- lib/active_record_host_pool/pool_proxy.rb
- test/test_arhp.rb
- In #48, `release_connection` was overridden for Rails 5 compatibility.
- This causes connection leakage in Rails 4.2, which uses `Thread.current.object_id` ([source](https://github.com/rails/rails/blob/v4.2.11.1/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L442)) as the key, unlike Rails 5+ which uses `Thread.current` ([source](https://github.com/rails/rails/blob/v5.2.4.2/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L401)) as the key.
- Override `release_connection` in an argument-agnostic manner to fix this.
@bquorning @pschambacher @grosser
> Fix release_connection rails 4.2 compatibility

- Changelog.md
- gemfiles/rails4.2.gemfile.lock
- gemfiles/rails5.0.gemfile.lock
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- gemfiles/rails6.0.gemfile.lock
- lib/active_record_host_pool/version.rb
Fixed: Fix connection leakage when calling `release_connection` on pre-Rails 5 applications: #58
> Bump to v1.0.1

- Changelog.md
- lib/active_record_host_pool.rb
- lib/active_record_host_pool/clear_query_cache_patch.rb
- test/database.yml
- test/helper.rb
- test/schema.rb
- test/test_arhp.rb
This PR patches `ActiveRecord::Base.clear_query_caches_for_current_thread` to restore the connection's database after it is done. Otherwise it's possible for a Mysql2Adapter instance's database to be changed out from under it during an operation (e.g. insert, update, delete, truncate, etc).
This PR is an alternate to PR #60. 
That PR resolves the general issue but loses out on an optimization to reduce the number of DB connections needed. This PR keeps the optimization, but leave the risk that this issue could show up again if new code paths are introduced to ActiveRecord or in gems that exercise the problematic code path.
Consider using this gem and [`active_record_shards`](http://github.com/zendesk/active_record_shards) gem. You may have this set up:
```ruby
class UnsharedModel < …
```
> Rails 6: Patch ActiveRecord::Base.clear_query_caches_for_current_thread 

- Changelog.md
- active_record_host_pool.gemspec
- gemfiles/rails4.2.gemfile.lock
- gemfiles/rails5.0.gemfile.lock
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- gemfiles/rails6.0.gemfile.lock
- lib/active_record_host_pool/version.rb
A new file was added to the repository in #61, but it wasn't reflected in the gemspec – so the released v1.0.2 doesn't work.
This PR fixes the gemspec and bumps the version to 1.0.3.
> Add missing file to gem

- .github/workflows/ci.yml
Add 2.7 in the list of ruby-versions used for the tests. 2.7 is also the oldest maintained version
Excluding the combination AR 4.2 and Ruby 2.7 due to failures because of `BigDecimal undefined method new`, don't think it's worth fixing.
Depends on: https://github.com/zendesk/active_record_host_pool/pull/75
> Add Ruby 2.7 in the tests

- .github/workflows/ci.yml
- .rubocop.yml
Currently supporting until Ruby 2.7, so using that version for linting.
Older Ruby versions are already EOL
Depends on: https://github.com/zendesk/active_record_host_pool/pull/75
> Use a maintained Ruby version for linting

- .github/workflows/ci.yml
- .rubocop.yml
- Changelog.md
- active_record_host_pool.gemspec
Remove Ruby 2.4 and 2.5 which stopped being supported a long time ago.
RuboCop target changed to match the minimum supported, else RuboCop
complains.
The commit is taken from #78, but I didn’t want to force push such changes to @anitsirc’s branch.
> Remove old Ruby versions

- test/database.yml
- test/helper.rb
- test/schema.rb
- test/test_arhp.rb
- test/test_arhp_wrong_db.rb
We've rewritten the tests to make it clearer what, exactly, they're testing and why they work the way that they do.
We renamed the database configuration keys from `test_host_1_db_1` to `test_pool_1_db_a`. Renaming `host` to `pool` feels better because each database configuration has the exact same host (`host: <%= mysql.host %>`)
We changed model names from things like `Test1` to `Pool1DbA` to make it clear that the model shares a connection pool with other models that start with `Pool1` and that it uses database  `A`.
This should help us work on making this gem `Rails 6.1` compatible because failing tests will be easier to diagnose without having to refer back to the model declarations to know which pool and database they refer to.
Co-authored-by: Cristina Matonte …
> Refactor tests

- active_record_host_pool.gemspec
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- gemfiles/rails6.0.gemfile.lock
- lib/active_record_host_pool/pool_proxy.rb
- test/helper.rb
Setting explicit version requirements on Minitest and Mocha, so we can get rid of some old code. Also removing a piece of code necessary only for Rails > 4.1 which we don’t support anymore.
> Some cleanups

- .github/CODEOWNERS
The ruby-core team are the primary team owners. The database-gem-owners
group remains as it's filled with champions that can push through change
without being blocked by ruby-core.
> Add ruby-core team as default codeowner

- .github/workflows/ci.yml
- lib/active_record_host_pool/connection_adapter_mixin.rb
- test/helper.rb
- test/test_arhp.rb
- test/test_arhp_legacy_connection_handling_only_tests.rb
We want to start testing Rails 6.1 with `legacy_connection_handling = false`. This keeps `legacy_connection_handling = true` by default in the CI but it can be passed in as an ENV variable to test it locally.
> Allow testing Rails 6.1 with legacy_connection_handling = false

- .github/workflows/ci.yml
- Changelog.md
- lib/active_record_host_pool/clear_query_cache_patch.rb
- test/helper.rb
- test/schema.rb
- test/test_arhp.rb
- test/test_arhp_caching.rb
- test/test_arhp_with_non_legacy_connection_handling.rb
- test/test_arhp_wrong_db.rb
- test/three_tier_database.yml
This PR adds support for Rails 6.1 when `legacy_connection_handling=false`
It's tested with the new multiple database functionality for sharded & unsharded models and with both writing and reading roles:
```ruby
class AbstractPool1DbA < ActiveRecord::Base
self.abstract_class = true
connects_to database: { writing: :test_pool_1_db_a, reading: :test_pool_1_db_a_replica }
end
class Pool1DbA < AbstractPool1DbA
self.table_name = "tests"
end
... 
class AbstractShardedModel < ActiveRecord::Base
self.abstract_class = true
connects_to shards: {
default: { writing: :test_pool_1_db_shard_a },
shard_b: { writing: :test_pool_1_db_shard_b, reading: :test_pool_1_db_shard_b_replica },
shard_c: { writing: :test_pool_1_db_shard_c, reading: :test_pool_1_db_shard_c_replica },
shard_d: { writing: …
```
> Add support for Rails 6.1 when legacy_connection_handling = false

- Changelog.md
- active_record_host_pool.gemspec
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- gemfiles/rails6.0.gemfile.lock
- gemfiles/rails6.1.gemfile.lock
- lib/active_record_host_pool/version.rb
Ensure that recently added files "lib/active_record_host_pool/pool_proxy_6_1.rb" and "lib/active_record_host_pool/pool_proxy_legacy.rb" are built into the shipped gem.
> Add missing files into the shipped gem

- .github/workflows/ci.yml
- Changelog.md
Start testing Rails 6.1 with Ruby 3.0 and 3.1
> Test Rails 6.1 with Ruby 3.0 & 3.1

- .github/workflows/publish.yml
Creates a workflow for publishing to the public Zendesk RubyGems account.
Uses the workflow from the public `gw` gem. `gw`'s [ruby-gem-publication readme](https://github.com/zendesk/gw/blob/main/ruby-gem-publication/README.md)
> Add workflow for pushing to Ruby Gems

- Rakefile
Calling `rake release` will:
- build
- tag (if everything has been committed)
- push to the repo
- push the gem to rubygems
Setting gem_push to false will skip the last step. We want to skip this because this is handled by a github workflow instead.
Co-authored-by: Benjamin Quorning <bquorning@zendesk.com>
> Set gem_push to false

- test/helper.rb
- test/test_thread_safety.rb
Additional test to establish confidence in the thread safety of this library.
No changes to the library code were necessary!
ActiveRecordHostPool doesn't appear to mess with how connections are initially checked out so each thread is allocated its own connection allowing it to switch database as desired without affecting other threads.
> Thread safety test passes with no changes

- test/test_thread_safety.rb
These thread tests are consistently failing when run with Rails 6.1 and `LEGACY_CONNECTION_HANDLING=false`.
> Disable ThreadSafetyTest for LCH=false

- active_record_host_pool.gemspec
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- gemfiles/rails6.0.gemfile.lock
- gemfiles/rails6.1.gemfile.lock
- gemfiles/rails7.0.gemfile.lock
- test/helper.rb
- test/test_arhp.rb
This PR removes the gems Shoulda and Mocha. I think Shoulda was actually never used and as for Mocha… We can easily use Minitest‘s own `#stub` method instead of Mocha’s `#stubs`, and the [minitest-mock_expectations](https://github.com/bogdanvlviv/minitest-mock_expectations) gem is a way, way smaller dependency than Mocha and yet it provides just the right amount of “syntactic sugar” for mocking. Methods like `refute_called`, `assert_called` and `assert_called_with`.
> Rethink test gems

- lib/active_record_host_pool/connection_adapter_mixin.rb
Rails 7 introduced an `async` keyword argument to the `#execute` method so we get keyword errors unless we splat in the kwargs:
```ruby
def execute(sql, name = nil, async: false)
raw_execute(sql, name, async: async)
end
```
> Splat kwargs on #execute

- Changelog.md
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- gemfiles/rails6.0.gemfile.lock
- gemfiles/rails6.1.gemfile.lock
- gemfiles/rails7.0.gemfile.lock
- lib/active_record_host_pool/clear_query_cache_patch.rb
- lib/active_record_host_pool/version.rb
Fix the patch for `ActiveRecord::Base.clear_query_caches_for_current_thread` to work correctly right after the creation of a new connection pool.
> Fix clear_query_caches_for_current_thread

- active_record_host_pool.gemspec
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- gemfiles/rails6.0.gemfile.lock
- gemfiles/rails6.1.gemfile.lock
- gemfiles/rails7.0.gemfile.lock
- test/helper.rb
I seem to always add `fail-fast`, `line`, and `pry-byebug` so it would be nice if they were always included. We need to use `pry-byebug ~> 3.9` until we drop Ruby 2.6.
> Add some gems for test/development

- test/test_arhp_with_non_legacy_connection_handling.rb
Let's test that the sharded models are created correctly even when nesting the shard switching.
> More robustly test shard switching

- test/test_arhp_with_non_legacy_connection_handling.rb
ARHP should _only_ call `select_db` when necessary. If it is calling `select_db` superfluously then it's possible Rails added a call to `connection` somewhere that is switching the databases on us and should be investigated.
Co-authored-by: Benjamin Quorning <bquorning@zendesk.com>
> Test that db switching happens only when we expect

- lib/active_record_host_pool/clear_query_cache_patch.rb
- test/test_arhp_caching.rb
I believe the underlying problem is that Rails calls `clear_query_caches_for_current_thread` and thus `pool.connection` in the middle of a database transaction. Because `pool.connection` hits the `ConnectionProxy` we end up setting `_host_pool_current_database` and possibly switching databases under us.
Instead of calling `connection` on pool we can call `_unproxied_connection` to bypass the connection proxy and let Rails do its thing without switching dbs.
We only need to patch `clear_query_caches_for_current_thread` in Rails 6.0 because this is the entire method:
```ruby
def clear_query_caches_for_current_thread
ActiveRecord::Base.connection_handlers.each_value do |handler|
handler.connection_pool_list.each do |pool|
pool.connection.clear_query_cache if pool.active_connection?
end
end …
```
> Simplify clear_query_cache_patch

- test/test_thread_safety.rb
Reverts commit 2a94a5a6fd4dcf77c956f47f11a910639ec98991. These thread tests were consistently failing when run with Rails 6.1 and `LEGACY_CONNECTION_HANDLING=false`. But the problems seem to have been fixed in v1.2.2 by commit 4a449154af67e67bb174dbcd181a282fe4e3bec5.
> Enable ThreadSafetyTest for LCH=false

- lib/active_record_host_pool/connection_adapter_mixin.rb
/Users/ktsanaktsidis/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/active_record_host_pool-1.2.3/lib/active_record_host_pool/connection_adapter_mixin.rb:36: warning: Skipping set of ruby2_keywords flag for execute_with_switching (method accepts keywords or method does not accept argument splat)
When using ruby2_keywords, your method should not actually accept keywords itself. It's designed to be used on methods accepting *args only.
> Fix warning about ruby2_keywords usage

- Changelog.md
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- gemfiles/rails6.0.gemfile.lock
- gemfiles/rails6.1.gemfile.lock
- gemfiles/rails7.0.gemfile.lock
- lib/active_record_host_pool/version.rb
- Fixed the warning when using `ruby2_keywords` on `execute_with_switching`.
- Simplified the `clear_query_caches_for_current_thread` patch.
> Release v1.2.4

- Rakefile
- active_record_host_pool.gemspec
- gemfiles/common.rb
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- gemfiles/rails6.0.gemfile.lock
- gemfiles/rails6.1.gemfile.lock
- gemfiles/rails7.0.gemfile.lock
Removing `bump` seems simpler, imo, to modify the version file by hand, bundle, etc.
We've decided to move development dependencies from the gemspec to the (common) gemfile. Occasionally development dependencies (for one reason or another) need to be define in the common gemfile so having them in two places gets confusing.
> Remove Bump gem, move development dependencies to Gemfile

- Changelog.md
- gemfiles/rails5.1.gemfile.lock
- gemfiles/rails5.2.gemfile.lock
- gemfiles/rails6.0.gemfile.lock
- gemfiles/rails6.1.gemfile.lock
- gemfiles/rails7.0.gemfile.lock
- lib/active_record_host_pool/connection_adapter_mixin.rb
- lib/active_record_host_pool/pool_proxy_6_1.rb
- lib/active_record_host_pool/pool_proxy_legacy.rb
- lib/active_record_host_pool/version.rb
Rails added a mutex around their `ConnectionPool#disconnect!` in Rails 6.1. Perhaps we should do the same?
Also removes `respond_to?(:clear_cache!)` and `respond_to?(:automatic_reconnect=)` since those method have been around since at least Rails 4. Perhaps I should rather do this in a separate PR?
> Mutex in PoolProxy#disconnect!

- Changelog.md
- Readme.md
- gemfiles/rails7.0_trilogy.gemfile
- gemfiles/rails7.0_trilogy.gemfile.lock
- lib/active_record_host_pool/connection_adapter_mixin.rb
- test/test_arhp_with_non_legacy_connection_handling.rb
Trilogy now has `select_db` as an alias for `change_db` which is the same method name that `mysql2` uses. Instead of conditionally determining the method name to use we can now just use the same method for both adapters.
> Remove change_db as the Trilogy database switching method

- Changelog.md
- gemfiles/rails6.1.gemfile.lock
- gemfiles/rails7.0_mysql2.gemfile.lock
- gemfiles/rails7.0_trilogy.gemfile.lock
- gemfiles/rails7.1_mysql2.gemfile.lock
- gemfiles/rails7.1_trilogy.gemfile.lock
- lib/active_record_host_pool/version.rb
Releases changes from https://github.com/zendesk/active_record_host_pool/pull/122, https://github.com/zendesk/active_record_host_pool/pull/123, and https://github.com/zendesk/active_record_host_pool/pull/125.
> bump version to 2.0.0.pre.1

- Changelog.md
- active_record_host_pool.gemspec
- gemfiles/rails6.1.gemfile.lock
- gemfiles/rails7.0_mysql2.gemfile.lock
- gemfiles/rails7.0_trilogy.gemfile.lock
- gemfiles/rails7.1_mysql2.gemfile.lock
- gemfiles/rails7.1_trilogy.gemfile.lock
- lib/active_record_host_pool/version.rb
Replace static list of files (which had to be updated manually and sometimes wasn’t, which broke the release process) with all `lib` files + docs.
> fix list of files in gemspec

- Changelog.md
- lib/active_record_host_pool/connection_adapter_mixin.rb
- test/database.yml
- test/test_arhp.rb
- test/three_tier_database.yml
`alias_method` used to be the way to patch methods in Ruby. The more modern, and elegant (imo), way is to use prepend.
ActiveRecordHostPool now uses prepend to patch `#execute`, `#raw_execute`, `#drop_database`, `#create_database`, and `#disconnect!`. Prepending is incompatible when also using `alias` or `alias_method` to patch those methods; avoid aliasing them to prevent an infinite loop.
Prepending **AND** aliasing is dangerous, if you prepend a method and later use alias to patch the same method you end up in an infinite loop:
```ruby
module GreetPatch
def greet
puts 'Hello'
super
end
end
class Foo
class << self
def greet
puts 'Hi'
end
end
end
Foo.singleton_class.prepend GreetPatch # Prepend greet.
Foo.singleton_class.class_eval do
def new_greet
puts 'Greetings'
original_greet
end …
```
> Switch from aliasing to prepend

- Changelog.md
- gemfiles/rails6.1.gemfile.lock
- gemfiles/rails7.0_mysql2.gemfile.lock
- gemfiles/rails7.0_trilogy.gemfile.lock
- gemfiles/rails7.1_mysql2.gemfile.lock
- gemfiles/rails7.1_trilogy.gemfile.lock
- lib/active_record_host_pool/version.rb
- Switch from usage of alias_method to use prepend.
- Drops support for Ruby < 3.0.
> Release v2.1.0

- .gitignore
- Changelog.md
- Gemfile.lock
- gemfiles/rails6.1_mysql2.gemfile.lock
- gemfiles/rails6.1_trilogy.gemfile.lock
- gemfiles/rails7.0_mysql2.gemfile.lock
- gemfiles/rails7.0_trilogy.gemfile.lock
- gemfiles/rails7.1_mysql2.gemfile.lock
- gemfiles/rails7.1_trilogy.gemfile.lock
- lib/active_record_host_pool/version.rb
- Support for Ruby 3.0.
- Rails 6.1 testing with Trilogy.
- Fixed using ActiveRecordHostPool and the `activerecord-trilogy-adapter v3.1+`.
-  ActiveRecordHostPool will now raise an exception if you try to use a version of `activerecord-trilogy-adapter < 3.1`.
> Release v2.2.0

- .gitignore
- lib/active_record_host_pool/connection_adapter_mixin.rb
- lib/active_record_host_pool/connection_proxy.rb
- test/test_arhp.rb
This PR:
1. Adds the Rails main lockfiles to `.gitignore`.
2. Renames `_host_pool_current_database` to `_host_pool_desired_database`.
3. Makes `_switch_connection` more readable.
See commit messages for more details.
> Small improvements

- .github/workflows/ci.yml
- Changelog.md
- gemfiles/rails7.2_mysql2.gemfile
- gemfiles/rails7.2_mysql2.gemfile.lock
- gemfiles/rails7.2_trilogy.gemfile
- gemfiles/rails7.2_trilogy.gemfile.lock
- lib/active_record_host_pool/connection_adapter_mixin.rb
- lib/active_record_host_pool/pool_proxy.rb
- test/test_arhp_caching.rb
Add support for Rails 7.2 & main. See the individual commits for more details.
`@connection` was renamed to `@raw_connection` on the database adapters
requiring us to conditionally define the `#_real_connection_object_id`
method. One returns `@connection.object_id` and the other
`@raw_connection.object_id`.
`#connection` was renamed to `#lease_connection` in Rails[^1]
`#with_connection` in Rails now leverages a new `ConnectionPool::Lease`
class[^2]. Essentially, the *real* connection pool has a connection
lease for the thread that may, or may not, have a **real** connection that may or
may not be "sticky". See the details about what that means in the Rails
commit. For ARHP purposes, we are essentially implementing the same
logic of `#with_connection` in Rails. We ask the real pool for its …
> Add support for Rails 7.2 & Rails main

- Changelog.md
- Gemfile.lock
- gemfiles/rails6.1_mysql2.gemfile.lock
- gemfiles/rails6.1_trilogy.gemfile.lock
- gemfiles/rails7.0_mysql2.gemfile.lock
- gemfiles/rails7.0_trilogy.gemfile.lock
- gemfiles/rails7.1_mysql2.gemfile.lock
- gemfiles/rails7.1_trilogy.gemfile.lock
- gemfiles/rails7.2_mysql2.gemfile.lock
- gemfiles/rails7.2_trilogy.gemfile.lock
- lib/active_record_host_pool/connection_adapter_mixin.rb
- lib/active_record_host_pool/version.rb
Whenever you call `raw_connection` Rails sets `@raw_connection_dirty = true` on the connection[^1]. The consequence of this is that Rails will not automatically reconnect a dirty connection because `reconnect_can_restore_state?` will return `false`[^2] which will set `reconnectable` to `false`[^3].
There's a comment in Rails that explains why they "dirty" the connection
whenever you call `raw_connection`:
```
Active Record cannot track if the database is getting modified using
this client. If that is the case, generally you'll want to invalidate
the query cache using +ActiveRecord::Base.clear_query_cache+.
```
Basically, I think what this means is that Rails can't be sure you
haven't messed up your query caches and you should manually call
`clear_query_cache` after calling …
> Call `#clean!` on the connection after switching, release v3.1.0

- Changelog.md
- Gemfile.lock
- gemfiles/rails6.1_mysql2.gemfile.lock
- gemfiles/rails6.1_trilogy.gemfile.lock
- gemfiles/rails7.0_mysql2.gemfile.lock
- gemfiles/rails7.0_trilogy.gemfile.lock
- gemfiles/rails7.1_mysql2.gemfile.lock
- gemfiles/rails7.1_trilogy.gemfile.lock
- gemfiles/rails7.2_mysql2.gemfile.lock
- gemfiles/rails7.2_trilogy.gemfile.lock
- lib/active_record_host_pool/connection_adapter_mixin.rb
- lib/active_record_host_pool/version.rb
- test/test_arhp.rb
I'm worried that calling `#clean!` will cause a performance hit. `#clean!`
will set `@raw_connection_dirty` to `false` but also set `@verified` to
`nil`[^1]. If `@verified` is `nil` then Rails may end up calling
`#verify!`[^2]. `#verify!` ends up calling `#active?` which will ping
the database[^3] causing another roundtrip.
Instead, I think we should call `#verified!` [^6] after cleaning so that
Rails doesn't have to re-verify for us. I believe this is safe because
the raw connection has to be verified before it's yielded to
`select_db`[^4] and if `select_db` ends up raising a connection-related
error then Rails will set `@verified` to `false` and `raise` [^5]
[^1]:(https://github.com/rails/rails/blob/171c4e4d377d9653a79d38c94bdfadf1a2c4c312/activerecord/lib/active_record/connection_adapte …
> Call `#verified!` after cleaning, release v3.2.0

- Changelog.md
- lib/active_record_host_pool/connection_adapter_mixin.rb
- lib/active_record_host_pool/pool_proxy.rb
- test/test_arhp.rb
- test/test_arhp_wrong_db.rb
- test/test_thread_safety.rb
Right now `ActiveRecordHostPool` never makes it into ActiveRecord's reconnect/retry logic. That's because that logic starts inside of the `#with_raw_connection` method[^1]. Here's a simplified look at the method:
```ruby
def with_raw_connection(allow_retry: false, materialize_transactions: true)
begin
yield @raw_connection # <-- The raw connection is yielded to the block.
rescue => exception
if reconnectable && retryable_connection_error?(exception)
reconnect!
retry
end
end
end
```
In host pool we patch `#raw_execute` to conduct the database switch:
```ruby
def raw_execute(...)
if _host_pool_desired_database && !_no_switch
_switch_connection
end
super
end
```
`#raw_execute` in Rails wraps the query in `#with_raw_connection` and
thus that's where we get the reconnect behavior:
```ruby
def …
```
> Move _switch_connection into with_raw_connection

- lib/active_record_host_pool/connection_adapter_mixin.rb
This may fix our test runs using the Rails `main` branch.
> Rails main branch is now 8.1.0.alpha

- test/test_arhp_wrong_db.rb
Fixes failing tests against Rails' main branch. See https://github.com/rails/rails/pull/53698.
> Fix tests to match new NoDatabaseError message

- .github/workflows/ci.yml
Dropped Ruby 3.1 in #162 but forgot to update the ruby-version when linting...
> Fix linting

- test/helper.rb
- test/test_arhp.rb
- test/test_arhp_caching.rb
- test/test_arhp_connection_handling.rb
- test/test_arhp_wrong_db.rb
- test/test_thread_safety.rb
We have a race condition that makes some of our tests flaky.
Previously we would call `Phenix.burn!` after _each_ test to drop all of the databases and then recreate them after. This cleared all of the records but also helped us with some tests where we expected some databases to not exist.
The problem with this is that ActiveRecord's connection pool reaper will, by default, start to kill connections after they're idle for 60 seconds and then reconnect[^1]. It also does this in a thread [^2].
What used to occasionally happen is that the reaper would kill a connection and then attempt to reconnect to the database _in between test runs_. i.e. _after_ the databases were dropped but _before_ they were created again. This would blow up.
This commit changes it so we no longer drop the databases …
> Delete all records instead of dropping dbs

- test/test_arhp.rb
- test/test_arhp_caching.rb
- test/test_arhp_connection_handling.rb
- test/test_thread_safety.rb
After some tests we clear all of the active connections[^1] just in case. Because of this, we might begin a test without an active connection and thus Rails will need to reconnect and call `_switch_connection`. That breaks tests that expect `_switch_connection` doesn't get called.
[^1]:(https://github.com/zendesk/active_record_host_pool/blob/327e0dbf2fe50192129755997e4e05e1f915d07c/test/test_arhp.rb#L24-L25)
> Fix flaky test

- .github/workflows/publish.yml
We don't have a `.ruby-version` file so we need to set the `ruby-version` in the action.
> Add ruby-version to setup-ruby

- Rakefile
Otherwise, we don’t have a `release` task when we try to publish the gem.
> require gem_tasks in rakefile

- test/test_arhp.rb
I use `_foo` to focus on specific tests in minitest but I forgot to remove this one.
> Remove `_foo` from test name
